name: 'Git Delta'
description: 'Show git diff with delta for a specific files against environments/branches/commits'
inputs:
  github_token:
    description: 'Github token for query github rest api if compare against environments'
    required: false
  environment:
    description: 'Environment to compare against'
    required: false
  branch:
    description: 'Branch to compare against'
    required: false
    default: 'main'
  commit:
    description: 'Commit to compare against'
    required: false
  files:
    description: |
      'Files to show the delta with separator as `\n`'
      For example: 
        files: |
          live/local/*
          live/stag/ec2/terragrunt.hcl
    required: false
    default: ""
  ignore_files:
    description: |
      "Ignore patterns for the delta with separator as `\n`"
            For example: 
        files_ignore: |
          *.zip
          */**/README.md
    required: false
    default: ""
  delta_output_path_depth:
    description: |
      Use `0` for the full path.
      Use a positive number (`> 0`) for breadth-first level:
      For example, `1` will return `/root/level1` from `/root/level1/level2/changed.txt`.
      Use a negative number (`< 0`) for depth-first level:
      For example, `-1` will return `/root/level1/level2` from `/root/level1/level2/changed.txt`.
    required: false
    default: 0
outputs:
  delta_files:
    description: 'File paths with the delta'
  is_detected:
    description: 'Bool to show if delta has been detected'
runs:
  using: 'docker'
  image: 'docker://jerry153fish/git-delta:latest'
